# Preprocessing data for ANN  

X shape will be (-1, 39)

In [3]:
# import pandas as pd
# import numpy as np


# def load_data(csv_path):
#     df = pd.read_csv(csv_path)
#     # Convert the string of predicted_vector to a proper list of floats
#     df["predicted_vector"] = df["predicted_vector"].apply(lambda x: eval(x))
#     df.drop(["path_to_image", "predicted_label"], axis=1, inplace=True)
#     return df


# def create_data_train_ANN(df, file_name_save):
#     # X = np.array([np.array(x).flatten() for x in test_df['predicted_vector']])
#     # y = df["true_label"]
#     # # create new dataframe with y and X
#     # ...
#     # # save the csv file
#     with open(file_name_save, "w") as f:
#         f.write("true_label,predicted_vector\n")
#         for i in range(len(df)):
#             f.write("{},{}\n".format(df["true_label"][i], df["predicted_vector"][i]))


# def create_data_train_DR_ANN(df, file_name_save):
#     # dimension reduce (reduce for classification task)
#     ...
#     # save the new dataframe
#     ...
#     # save the csv file


# def create_data_train_Transformer(df, file_name_save):
#     # transform X mn
#     # ...
#     # df["predicted_vector"] = df["predicted_vector"].apply(lambda x: x + np.argmax(x))   # [0.98, 0.01, 0.01] -> [0.98, 0.01, 0.01, 1, 0, 0]
#     #
#     with open(file_name_save, "w") as f:
#         f.write("true_label,predicted_vector\n")
#         for i in range(len(df)):
#             f.write("{},{}\n".format(df["true_label"][i], df["predicted_vector"][i]))


# test_df = load_data("~/Downloads/data_for_module2/test_not_aug.csv")

In [2]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.manifold import TSNE

def load_data(csv_path):
    df = pd.read_csv(csv_path)
    # Convert the string of predicted_vector to a proper list of floats
    df["predicted_vector"] = df["predicted_vector"].apply(lambda x: eval(x))
    df.drop(["path_to_image", "predicted_label"], axis=1, inplace=True)
    return df

def create_data_train_ANN(df, file_name_save):
    X = np.array([np.array(x).flatten() for x in df['predicted_vector']])
    y = df["label"]
    
    # create new dataframe with y and X
    new_df = pd.DataFrame(X)
    new_df['label'] = y
    
    # save the csv file
    new_df.to_csv(file_name_save, index=False)
    # with open(file_name_save, 'w') as f:
    #     f.write("label,predicted_vector\n")
    #     for i in range(len(df)):
    #         f.write("{},{}\n".format(df["label"][i], df["predicted_vector"][i]))

def create_data_train_DR_ANN(df, file_name_save):
    X = np.array([np.array(x).flatten() for x in df['predicted_vector']])
    y = df["label"]
    
    # dimension reduce (reduce for classification task)
    # Option 1: PCA
    pca = PCA(n_components=0.95)  # Keep 95% of variance
    X_pca = pca.fit_transform(X)
    
    # Option 2: LDA
    # lda = LDA(n_components=min(len(set(y) - 1), X.shape[1]))
    # X_lda = lda.fit_transform(X, y)
    
    # Option 3: t-SNE
    # tsne = TSNE(n_components=??, random_state=42)
    # X_tsne = tsne.fit_transform(X)
    
    # Choose one of the above methods or combine them
    X_reduced = X_pca  # or X_lda or X_tsne
    # X_reduced = X_lda

    # save the new dataframe
    new_df = pd.DataFrame(X_reduced)
    new_df['label'] = y
    
    # save the csv file
    new_df.to_csv(file_name_save, index=False)

def create_data_train_Transformer(df, file_name_save):
    # transform X
    # df["predicted_vector"] = df["predicted_vector"].apply(lambda x: x + [1 if i == np.argmax(x) else 0 for i in range(len(x))])
    
    with open(file_name_save, 'w') as f:
        f.write("label,predicted_vector\n")
        for i in range(len(df)):
            f.write("{},{}\n".format(df["label"][i], df["predicted_vector"][i]))

# fix lai de chuan bi du lieu cho model transformer
test_df = load_data("~/Downloads/data_for_module2/test_not_aug.csv")

%cd ~/Downloads/data_for_module2
# Example usage
create_data_train_ANN(test_df, "df_ann_test_data.csv")
create_data_train_DR_ANN(test_df, "df_dr_ann_test_data.csv")
create_data_train_Transformer(test_df, "df_transformer_test_data.csv")

/home/harito/Downloads/data_for_module2


In [3]:
test_df.head()

label                                   predicted_vector
0      2  [[-4.326164722442627, -3.336007833480835, 7.18...
1      2  [[-6.909836292266846, -0.10185574740171432, 5....
2      2  [[-5.408203125, -1.994320034980774, 6.49257707...
3      2  [[-5.0263237953186035, -2.326490879058838, 5.7...
4      2  [[-6.983879566192627, 5.36437463760376, -0.036...

In [5]:
X_flatten = np.array([np.array(x).flatten() for x in test_df['predicted_vector']])
print(X_flatten.shape)
print(X_flatten[0])

(272, 39)
[ -4.32616472  -3.33600783   7.18650198  -7.65047455   2.33006692
   2.62367773  -9.80081081   3.64352703   3.52408385  -9.21626759
   0.63079673   6.04045963  -9.7001133    0.41957453   6.2976532
  -9.94150734   0.20350178   6.4670887   -6.07121134  -1.14298558
   6.11337137  -6.44479179  -0.41365007   5.78346777 -10.93817234
   5.00597095   2.6089623  -11.15839767   3.30436683   3.34848619
  -5.71532249  -1.46101451   5.17608023  -8.53942394  -1.72039652
   7.67711163  -8.01943398   2.24353075   3.20311427]


In [6]:
X_transformer = np.array([np.array(x) for x in test_df['predicted_vector']])
print(X_transformer.shape)
print(X_transformer[0])

(272, 13, 3)
[[ -4.32616472  -3.33600783   7.18650198]
 [ -7.65047455   2.33006692   2.62367773]
 [ -9.80081081   3.64352703   3.52408385]
 [ -9.21626759   0.63079673   6.04045963]
 [ -9.7001133    0.41957453   6.2976532 ]
 [ -9.94150734   0.20350178   6.4670887 ]
 [ -6.07121134  -1.14298558   6.11337137]
 [ -6.44479179  -0.41365007   5.78346777]
 [-10.93817234   5.00597095   2.6089623 ]
 [-11.15839767   3.30436683   3.34848619]
 [ -5.71532249  -1.46101451   5.17608023]
 [ -8.53942394  -1.72039652   7.67711163]
 [ -8.01943398   2.24353075   3.20311427]]


# Preprocessing data for DR + ANN  

X shape will be (-1, xx)

# Preprocessing data for Transformer  

X shape will be (-1, 13, xx)